apiVersion: batch/v1
kind: Job
metadata:
  name: iics
spec:
  template:
    spec:
      containers:
      - name: iics
        image: jsrfntd/demo:v5
        command: ["python", "/app/main.py"]
      restartPolicy: OnFailure
  backoffLimit: 4